# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

compiler: gcc

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/astroconda'
        - CONDA_DEPENDENCIES='pytest sphinx'
        - PIP_DEPENDENCIES=''
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - EVENT_TYPE='push pull_request'

    matrix:
        - SETUP_CMD='install'
        - SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # build sphinx documentation with warnings
        - os: linux
          env: SETUP_CMD='build_sphinx'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx_rtd_theme stsci_rtd_theme sphinx-automodapi'

        # PEP8 check with flake8 (only once, i.e. "os: linux")
        - os: linux
          env: MAIN_CMD='flake8 --count'
               SETUP_CMD='packagename' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES

    allow_failures:
        # PEP8 will fail for numerous reasons. Ignore it.
        - env: MAIN_CMD='flake8 --count'
               SETUP_CMD='packagename' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD

deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: i4E66KhDD/MkPTHLDUV6dk2OTqingG9/k2sxctnPeVtml5O7NRjJ0QwZeAannkHuFWCjRZ+BpJ2g4JZ6VL+BBcxifVKcxwxGJ8NfKAPmb9LLuqkLI7wPkSrmjvWuq9MLR3NDq4+oqm8EyvVdvDnTPFsTnnVCg3Y0M4tvfOea3szsZIPYNpjOyOtztHFxqXhda3ZvvdE2N9p926z7qhOLSzl0YB7AOlX1qYzpUT7xWX5LT1/DILGFvee1AOq6tcIUXEfvA1vvMkecZLI/CkUE6aMlWDpM0iaEwnix8GyhT9rAarXWXDakuLmQzGdGCq/T8469lljV5sJMZt8gEMUQumpHFODRL3yW6lLph1vZbWXmS+PgUk5kHf8IB1iQwdSPgOBhNfEtbmTcFQCJLaxRQPdyoEb/lh4ZfVV1WjrghMIUf6YAL4NWPRmiQWgyIREBJsS3li6j7XnRvOigIDJ/MOqHLB/4+YpSnrvNLXJrkQdy+t92FacZQrc0drARia3ImK0avzaV/1WCFnR4aQAyqv/XMGO0yuWQBKAFByeq4WGhi/Dd0ayjUFht6RfHH9S7c3NqfOYxtTsw7CHJozqd6Pi+ybEgi4J/+ITAuE27eWNGeFCyfc7OjlQqsbCLp574nDlJc31v8dQfSYJF2gyXGPEMEJRj7JudTq9zj3oLpbQ=
  on:
    branch: master
    tags: false
